export const tasks = [
  {
    id: "UUID-note-1",
    title: "Primera Nota",
    description: "This is my first note description",
    image: "",
    drag: "",
    created_at: "25/4/2024, 8:22:57 p.m.",
    updated_at: "25/4/2024, 8:22:57 p.m.",
    favorite: false,
    tags: ["javascript", "typescript", "node", "express", "nest"],
    toDoList: [
      {
        id: "UUID-task-1-1",
        label: "Primera tarea de mi primera nota",
        done: false,
        created_at: "25/4/2024, 8:22:57 p.m.",
        updated_at: "25/4/2024, 8:22:57 p.m.",
      },
      {
        id: "UUID-task-1-2",
        label: "Segunda tarea de mi primera nota",
        done: false,
        created_at: "25/4/2024, 8:22:57 p.m.",
        updated_at: "25/4/2024, 8:22:57 p.m.",
      },
    ],
  },
  {
    id: "UUID-note-2",
    title: "Segunda Nota",
    description: "This is my second note description",
    image: "",
    drag: "",
    created_at: "25/4/2024, 8:22:57 p.m.",
    updated_at: "25/4/2024, 8:22:57 p.m.",
    favorite: false,
    tags: ["javascript", "typescript", "node", "react", "next"],
    toDoList: [
      {
        id: "UUID-task-2-1",
        label: "Primera tarea de mi segunda nota",
        done: false,
        created_at: "25/4/2024, 8:22:57 p.m.",
        updated_at: "25/4/2024, 8:22:57 p.m.",
      },
      {
        id: "UUID-task-2-2",
        label: "Segunda tarea de mi segunda nota",
        done: false,
        created_at: "25/4/2024, 8:22:57 p.m.",
        updated_at: "25/4/2024, 8:22:57 p.m.",
      },
    ],
  },
];
